name: GitHub Actions Demo
on:
  push:

jobs:
  Run-Lint_Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.3

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

  Run-Auth-Tests:
    needs: Run-Lint_Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.3

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run Auth tests
        id: auth-tests
        run: |
          npm run cypress -- --spec "./cypress/e2e/Login_tests/login_testing.cy.ts" --browser chrome
          echo "auth-tests=success" >> $GITHUB_ENV

  Run-UI-Tests:
    needs: Run-Auth-Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.3

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run UI tests
        if: ${{ success() && needs.Run-Auth-Tests.outputs.auth-tests == 'success' }}
        run: npm run cypress -- --browser chrome
